### ISSUE TITLE
relocate openfire-restapi

### ISSUE THREAD

**Issue by therealkevink** [seamus-45/openfire-restapi#3]
Hi,

In my environment I can't install under /usr/local, and  "python setup.py install" gives me and error that includes

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
 

... but "--install-dir" doesn't work anywhere in the command.  Whether I put "--install-dir $DIR" at the end, after "setup.py", or after "python", I get an error.

**Comment by seamus-45** [comment]
Greetings!
I don't know why this dir does not exists.
You can try this command before install:
`sudo install -d /usr/local/lib/python2.7/dist-packages`

or try:

`sudo python setup.py install --prefix=/usr --install-lib=/usr/lib/python2.7/dist-packages/`

another option is to use virual environment, as described in [updated readme](https://github.com/seamus-45/openfire-restapi/blob/master/README.md).

**Comment by therealkevink** [comment]
I missed the initial notification but saw the   'close issue' one this morning.  Sorry about that and thank you for your suggestions.
